version: '3.8'
services:
  postgres-container:
    image: postgres:latest
    environment:
      POSTGRES_DB: distribution_center
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
